import { formatClock, type TranscriptSegment } from '../parsers/index.js';

export interface TimelineEntry {
  time: string;
  event: string;
}

export interface Definition {
  term: string;
  definition: string;
}

export interface QuizItem {
  question: string;
  answer: string;
}

export interface Flashcard {
  question: string;
  answer: string;
}

export interface NoteData {
  title: string;
  executiveSummary: string;
  keyConcepts: string[];
  timeline: TimelineEntry[];
  definitions: Definition[];
  reviewQuestions: string[];
  quiz: QuizItem[];
  flashcards: Flashcard[];
  actionItems: string[];
}

export interface NoteMeta {
  /** Human-readable date/time of the session. */
  date: string;
  /** Source file path or live session id. */
  source: string;
  /** e.g. "gemini (gemini-2.5-flash)" or "offline fallback (no AI configured)". */
  generatedBy: string;
  /** Inline raw transcript appendix. */
  transcript?: string;
  /** Alternatively, a path/link to the raw transcript file. */
  transcriptRef?: string;
}

const NONE = '_None captured._';

export function renderNote(data: NoteData, meta: NoteMeta): string {
  const out: string[] = [];
  const section = (title: string) => {
    out.push('', `## ${title}`, '');
  };

  out.push(`# ${data.title || 'Untitled lecture'}`);
  out.push('');
  out.push(`- **Date:** ${meta.date}`);
  out.push(`- **Source:** ${meta.source}`);
  out.push(`- **Generated by:** ${meta.generatedBy}`);

  section('Executive Summary');
  out.push(data.executiveSummary?.trim() || NONE);

  section('Key Concepts');
  if (data.keyConcepts.length === 0) out.push(NONE);
  else for (const c of data.keyConcepts) out.push(`- ${c}`);

  section('Timeline');
  if (data.timeline.length === 0) out.push(NONE);
  else for (const t of data.timeline) out.push(`- **${t.time}** — ${t.event}`);

  section('Important Definitions');
  if (data.definitions.length === 0) out.push(NONE);
  else for (const d of data.definitions) out.push(`- **${d.term}** — ${d.definition}`);

  section('Questions to Review');
  if (data.reviewQuestions.length === 0) out.push(NONE);
  else data.reviewQuestions.forEach((q, i) => out.push(`${i + 1}. ${q}`));

  section('Quiz');
  if (data.quiz.length === 0) out.push(NONE);
  else {
    data.quiz.forEach((q, i) => {
      out.push(`**Q${i + 1}. ${q.question}**`, '');
      out.push(`> **Answer:** ${q.answer}`, '');
    });
  }

  section('Flashcards');
  if (data.flashcards.length === 0) out.push(NONE);
  else {
    for (const f of data.flashcards) {
      out.push(`- **Q:** ${f.question}`);
      out.push(`  **A:** ${f.answer}`);
    }
  }

  section('Action Items');
  if (data.actionItems.length === 0) out.push(NONE);
  else for (const a of data.actionItems) out.push(`- [ ] ${a}`);

  section('Raw Transcript');
  if (meta.transcript) {
    out.push('```text');
    out.push(meta.transcript.trim());
    out.push('```');
  } else if (meta.transcriptRef) {
    out.push(`Raw transcript file: \`${meta.transcriptRef}\``);
  } else {
    out.push(NONE);
  }

  return out.join('\n') + '\n';
}

/** Coerces an untyped model response into a well-formed NoteData. */
export function normalizeNoteData(raw: unknown, fallbackTitle: string): NoteData {
  const obj = (raw ?? {}) as Record<string, unknown>;
  const str = (v: unknown): string => (typeof v === 'string' ? v.trim() : '');
  const strArr = (v: unknown): string[] =>
    Array.isArray(v) ? v.map(str).filter(Boolean) : [];
  const pairArr = <T>(v: unknown, map: (o: Record<string, unknown>) => T | null): T[] =>
    Array.isArray(v)
      ? v
          .map((item) =>
            item && typeof item === 'object'
              ? map(item as Record<string, unknown>)
              : null
          )
          .filter((x): x is T => x !== null)
      : [];

  return {
    title: str(obj.title) || fallbackTitle,
    executiveSummary: str(obj.executiveSummary),
    keyConcepts: strArr(obj.keyConcepts),
    timeline: pairArr(obj.timeline, (o) => {
      const time = str(o.time);
      const event = str(o.event);
      return event ? { time: time || '-', event } : null;
    }),
    definitions: pairArr(obj.definitions, (o) => {
      const term = str(o.term);
      const definition = str(o.definition);
      return term && definition ? { term, definition } : null;
    }),
    reviewQuestions: strArr(obj.reviewQuestions),
    quiz: pairArr(obj.quiz, (o) => {
      const question = str(o.question);
      const answer = str(o.answer);
      return question && answer ? { question, answer } : null;
    }),
    flashcards: pairArr(obj.flashcards, (o) => {
      const question = str(o.question);
      const answer = str(o.answer);
      return question && answer ? { question, answer } : null;
    }),
    actionItems: strArr(obj.actionItems),
  };
}

const STOP_WORDS = new Set([
  'about', 'after', 'again', 'their', 'there', 'these', 'thing', 'things',
  'think', 'those', 'where', 'which', 'while', 'would', 'could', 'should',
  'because', 'before', 'between', 'going', 'really', 'right', 'today',
  'everyone', 'welcome', 'thanks', 'thank', 'okay', 'please', 'question',
  'questions', 'little', 'something', 'anything', 'everything',
]);

/**
 * Heuristic, zero-cost note built when AI is unavailable (no key, quota hit,
 * or API error). Extractive only — never invents content.
 */
export function fallbackNoteData(
  segments: TranscriptSegment[],
  titleHint: string
): NoteData {
  const text = segments.map((s) => s.text).join(' ');
  const sentences = text.match(/[^.!?\n]+[.!?]+/g) ?? (text ? [text] : []);
  const executiveSummary =
    sentences.slice(0, 4).join(' ').trim().slice(0, 600) ||
    'No transcript content was available for a summary.';

  const timeline: TimelineEntry[] = [];
  const step = Math.max(1, Math.floor(segments.length / 6));
  for (let i = 0; i < segments.length && timeline.length < 6; i += step) {
    const seg = segments[i];
    if (seg.start === undefined) continue;
    timeline.push({
      time: formatClock(seg.start),
      event: seg.text.slice(0, 80),
    });
  }

  return {
    title: titleHint,
    executiveSummary,
    keyConcepts: topWords(text, 8),
    timeline,
    definitions: [],
    reviewQuestions: [
      'What were the main topics of this session?',
      'Which terms or concepts were unfamiliar to you?',
      'What would you ask the instructor next time?',
    ],
    quiz: [],
    flashcards: [],
    actionItems: [
      'Re-read the transcript and highlight the key passages.',
      'Add a GEMINI_API_KEY to .env to get AI summaries, quizzes and flashcards.',
    ],
  };
}

function topWords(text: string, n: number): string[] {
  const counts = new Map<string, number>();
  for (const match of text.toLowerCase().matchAll(/\p{L}{5,}/gu)) {
    const word = match[0];
    if (STOP_WORDS.has(word)) continue;
    counts.set(word, (counts.get(word) ?? 0) + 1);
  }
  return [...counts.entries()]
    .filter(([, c]) => c >= 2)
    .sort((a, b) => b[1] - a[1])
    .slice(0, n)
    .map(([w]) => w[0].toUpperCase() + w.slice(1));
}

export function slugify(title: string): string {
  return (
    title
      .normalize('NFKD')
      .replace(/[̀-ͯ]/g, '')
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 60) || 'note'
  );
}
